# Delete redis data
# docker ps
# docker exec -it NAME redis-cli FLUSHALL
version: '2'
services:
  db:
    image: mysql:5.7.17
    ports:
      - "3374:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file: ../.env
  redis:
    image: redis:3.0
    ports:
      - "6374:6379"
    restart: always
volumes:
  db_data:
